# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'retina' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSS3'
  pod 'AWSMobileClient'
  # Pods for retina

  target 'retinaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'retinaUITests' do
    # Pods for testing
  end

end
